kvstore.wal.path=/Users/prashantverma/kvstore_data/wal
kvstore.sstable.path=/Users/prashantverma/kvstore_data/sstables
kvstore.memtable.max-size-bytes=4096

# WAL settings
kvstore.wal.max-size-bytes=1048576
# Compaction settings
kvstore.compaction.trigger.file-count=2
kvstore.compaction.schedule.ms=10000

# --- Cluster Settings ---
# A comma-separated list of all nodes in the cluster.
kvstore.cluster.nodes=http://localhost:8080,http://localhost:8081,http://localhost:8082
# The URL of this specific node instance.
kvstore.cluster.current-node-url=http://localhost:8080
# The total number of copies to keep for each piece of data.
kvstore.cluster.replication-factor=3
# Designates this node as the one responsible for running background maintenance (compaction).
kvstore.cluster.is-maintenance-leader=true
