kvstore.wal.file=/Users/prashantverma/kvstore_data/wal.log
kvstore.sstable.path=/Users/prashantverma/kvstore_data/sstables
kvstore.memtable.max-size-bytes=4096

# Compaction settings
kvstore.compaction.trigger.file-count=4
kvstore.compaction.schedule.ms=10000
